on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:9.6
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24.0.1'
          elixir-version: '1.12.0'
      - run: mix deps.get
      - run: mix test